<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees [
   <!ELEMENT employees (employee+)>
   <!ELEMENT employee (id, name, department, designation, email, salary)>
   <!ELEMENT id (#PCDATA)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT department (#PCDATA)>
   <!ELEMENT designation (#PCDATA)>
   <!ELEMENT email (#PCDATA)>
   <!ELEMENT salary (#PCDATA)>
]>

<employees>
   <employee>
      <id>101</id>
      <name>Samyak Pusate</name>
      <department>Computer Technology</department>
      <designation>Software Engineer</designation>
      <email>samyak@gmail.com</email>
      <salary>55000</salary>
   </employee>
   <employee>
      <id>102</id>
      <name>Shlok Bhoyar</name>
      <department>Computer Science Engineering</department>
      <designation>Student</designation>
      <email>Shlok@gmail.com</email>
      <salary>60000</salary>
   </employee>
</employees>
